name: my_portfolio
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  animated_theme_switcher: ^2.0.6
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  google_fonts: ^6.1.0
  responsive_framework: ^0.1.7
  url_launcher: ^6.0.20
  flutter_riverpod: ^1.0.3

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4
  build_test: any


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/images/
    - assets/images/social/
    - assets/images/projects/
    - assets/images/technology/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/IotIcon.ttf